### ISSUE TITLE
加载项目时候出现依赖不能正常加载的问题!

### ISSUE THREAD

**Issue by baisedebing** [SenparcCoreFramework/SCF#21]
Microsoft.AspNetCore.App 出现黄色的感叹号，下载了所有的版本，没有什么用。
![QQ截图20191109045559](https://user-images.githubusercontent.com/26034137/68509950-4648df00-02ad-11ea-8ed9-baa0795ac2a8.png)

![QQ截图20191109054642](https://user-images.githubusercontent.com/26034137/68512828-66c86780-02b4-11ea-91e3-137aab206c6c.png)

**Comment by FrancisFYK** [comment]
在csproj文件中移除Microsoft.AspNetCore.App 引用即可，最新代码已经处理这个问题，感谢反馈。

**Comment by JeffreySu** [comment]
@baisedebing 已经合并到 master 分支，可以再测试一下。
