### ISSUE TITLE
无法登陆HttpContext 为null

### ISSUE THREAD

**Issue by passhk** [SenparcCoreFramework/SCF#23]

**Comment by passhk** [comment]
![微信图片_20191211110904](https://user-images.githubusercontent.com/36319119/70588155-cc3aab80-1c06-11ea-9eb8-55b49e772618.png)

**Comment by passhk** [comment]
方法 public virtual async Task LoginAsync(string userName, bool rememberMe, IEnumerable<string> roles)
var httpContext = _contextAccessor.Value.HttpContext;
值 为 null ，有时候 好用 有时不好用

**Comment by JeffreySu** [comment]
新版本应该都没有这个问题了吧？
