### ISSUE TITLE
时而出现的问题 输入登陆网址/admin/login

### ISSUE THREAD

**Issue by passhk** [SenparcCoreFramework/SCF#24]
![微信图片_20191211113506](https://user-images.githubusercontent.com/36319119/70589370-854eb500-1c0a-11ea-9481-f8822c80c10a.png)
![微信图片_20191211113506](https://user-images.githubusercontent.com/36319119/70589319-651ef600-1c0a-11ea-8765-9179f4ab98d9.png)
![微信图片_20191211113506](https://user-images.githubusercontent.com/36319119/70589433-a7483780-1c0a-11ea-909a-55d6832743ad.jpg)

**Comment by passhk** [comment]
InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

**Comment by passhk** [comment]
InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
![微信图片_20191211113937](https://user-images.githubusercontent.com/36319119/70589552-f1c9b400-1c0a-11ea-8bee-5fb539ac5d50.png)

**Comment by JeffreySu** [comment]
@passhk 有什么特别的环境条件吗？可以用新版本再测试一下，我这边没有碰到这个异常。

**Comment by passhk** [comment]
新版本 没这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jeffrey Su"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 上午10:18
收件人:&nbsp;"SenparcCoreFramework/SCF"<SCF@noreply.github.com&gt;;
抄送:&nbsp;"猪才怪"<415922875@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SenparcCoreFramework/SCF] 时而出现的问题 输入登陆网址/admin/login (#24)





 
@passhk 有什么特别的环境条件吗？可以用新版本再测试一下，我这边没有碰到这个异常。
