### ISSUE TITLE
这是需要install什么要，着急。。

### ISSUE THREAD

**Issue by xclyisen** [SenparcCoreFramework/SCF#8]
![tim 20190112005825](https://user-images.githubusercontent.com/15728845/51048273-80057680-1605-11e9-85ae-d65668de2c1a.png)

**Comment by JeffreySu** [comment]
第一次运行的时候，先执行 /Install 这个地址，系统会完成自动安装。

**Comment by xclyisen** [comment]
请问这个地址指的是什么地址？

**Comment by xclyisen** [comment]
地址栏输入 /Install  ,脑子是个好东西··
![tim 20190219235440](https://user-images.githubusercontent.com/15728845/53028442-d3d76b00-34a1-11e9-88a6-2ed14ade5f71.png)
